name: 01 - Building Blocks
on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: echo-hello
        run: echo "Hello, world!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: echo-goodbye
        run: echo "Goodbye, world!"

  failed-step:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1

  success-step:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "I will succeed"
          exit 0
